version: '3.7'


services:
  
  db:
    image: postgres:15
    restart: always 
    container_name: db
    command: -p 5435
    expose:
      - 5435
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
  
  api:
    container_name: qrmenu
    image: dchnkoo/qr-sys:0.0.1-ps
    command: ["./app.sh"]
    environment:
      # database
      - DATABASE_URL=postgresql+asyncpg://test:test@db:5435/test
      - DATABASE_URL_SYNC=postgresql://test:test@db:5435/test

      # for sending emails
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SENDER_EMAIL=example@gmail.com
      - SENDER_PASSWORD=your_password

      # CORS
      - CROS_ORIGINS=["http://localhost:5173"]
    ports:
      - "8000:8080"
    depends_on:
      - db
