version: '3.7'

services:
  re:
    image: redis
    container_name: re
    command: redis-server --requirepass redistest
    ports:
      - '6379:6379'

  db:
    image: postgres

    restart: always 

    container_name: db
    command: -p 5435
    expose:
      - 5435
    ports:
      - '5435:5432'
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test

  api:
    container_name: qrmenu
    image: dchnkoo/qr-sys
    env_file:
      - .env
    ports:

      - "8000:8080"
      - "5555:5555"
    depends_on:
      - db
      - re

