# Generated by Django 4.2.7 on 2023-11-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='restaurants',
        ),
    ]
